### PR TITLE
Remove boost.random dependency

### PR DESCRIPTION
**Pull request by mborland**
In standalone mode the functionality of `miller_rabin_test` is reduced to only those types that are compatible with `std::uniform_int_distribution`.

### CODE REVIEW

**Comment by ckormanyos** [comment]
> In standalone mode the functionality of `miller_rabin_test` is reduced to only those types that are compatible with `std::uniform_int_distribution`

> Porting from Boost.Random would be possible if needed, 

I think it will be quite a relief to remove the dependency on Boost.Random.

I'm not sure, but thinking out loud here. There are tests and at least one example that require wide integer types for testing Miller-Rabin. But basically these tests simple need a random uniform bit-stream genertor for N bits. With just a few lines of C++11 code, it should be possible to make or fashion a little utility from an integer distribution on the range (0,1) for N bits that could then be used in these tests and examples --- standalone or not. I can help if this is thought to be feasible.

**Comment by ckormanyos** [comment]
> have ported `uniform_int_distribution` and modernized the implementation to use C++11 internally removing any external dependencies. This breaks the dependency on Boost.Random with or without standalone mode.

I think it is a good detail/utility that removes a rather heavy dependency.

**Comment by mborland** [comment]
CI on this one is clean so pending review it should be good to go.

**Comment by mborland** [comment]
This is clean with the requested changes. Only failure is internal to the CI.

**Comment by ckormanyos** [comment]
Hi @mborland and @jzmaddock this is cool.

In another project I just experienced a problem because my project had (falsely) relied on the parasitic inclusion of some `Boost.Random` headers via the inclusion of `<boost/multiprecision/miller_rabin.hpp>`.

Although this is/was a problem in my particular project, it wouldn't surprise me if others experience such things in 1.79 down the road. Is it important for others? Can we announce explicitly in changes, as I think a few others might run into this nuance.

**Pull request merged**
