### PR TITLE
Fix for issue 499

### PR DESCRIPTION
**Pull request by mborland**
Replaced boost::lexical_cast with std::stol without updating the type of exception being caught

### CODE REVIEW

**Comment by jzmaddock** [comment]
Does this work?  strtoll is non-throwing.

**Comment by mborland** [comment]
> Does this work? strtoll is non-throwing.

This uses `stol` which throws `std::invalid_argument` like the issue was seeing as opposed to returning 0 like `strtol`. The catch block was only for `bad_lexical_cast` which was causing `std::invalid_argument` to propagate to the user.

**Comment by ckormanyos** [comment]
Thank you for going after this, Matt (@mborland)!

**Comment by yaroslavchahovets** [comment]
Hello!
I checked this fix (commit 60a40c598873c47e8e5e94d438eab1bc913741b0) and found the following.
1. It fixes the case when input string is "wrong".
2. It does not fix cases when input string is "12a3.4" and "1.2a34" (see https://github.com/boostorg/multiprecision/issues/499#issue-1398168644)
3. It introduces some regress. When input string has scientific notation, for example "3.4e1a2", the expected result is throwing the std::runtime_exception with the text "Unable to parse the string \"3.4e1a2\" as a floating point value.", whereas with this fix, the test program generates no exception, result is 34.

So I think this commit (60a40c5988) does a good job, but another commit(s) should be added to fix all the cases.
Previously I proposed the idea for fix  "12a3.4" and "1.2a34" cases here: https://github.com/boostorg/multiprecision/issues/499#issuecomment-1270023503

Thank you for your work, @mborland .

**Comment by mborland** [comment]
@yaroslavchahovets This next pair of commits should address your other cases. Thanks for the feedback.

**Comment by yaroslavchahovets** [comment]
Now all cases I reported previously ("wrong", "12a3.4", "1.2a34", "3.4e1a2") produce expected behavior.
But the cases "12L3.4", "12f3.4" produce wrong behavior (no exceptions, value is 12.4).
Also the cases "1.2L34", "1.2f34" produce wrong behavior (no exceptions, value is 1.00000002).

Thank you.

**Comment by yaroslavchahovets** [comment]
Hello. Commit https://github.com/boostorg/multiprecision/pull/502/commits/e1abb81da102d86046e8381bd78e27a67fad7b9a fixes behavior for cases "12L3.4", "12f3.4", thanks.
But for the 'normal' cases "1.2f", "12f", "12L" it throws an exception. I think the correct behavior for these cases is to produce values 1.2, 12, 12 respectively.

**Comment by yaroslavchahovets** [comment]
Or, alternatively, we can consider format with F,f,L,l suffixes illegal (as it was in boost 1.78.0 and earlier). In this case we should keep the behavior of commit https://github.com/boostorg/multiprecision/pull/502/commits/e1abb81da102d86046e8381bd78e27a67fad7b9a  and delete all the code which implements functionality of F,f,L,l suffixes.

**Comment by jzmaddock** [comment]
I would reasonably strongly favour keep suffixes as illegal: it's not clear what meaning they confer in a multiprecision context.

**Comment by yaroslavchahovets** [comment]
@jzmaddock Please consider integrate this pull request into the main repository

**Comment by jzmaddock** [comment]
Sorry for being late to review this, just checking this out, we still erroneously parse things like "23.5-3e-26"

**Comment by mborland** [comment]
@jzmaddock since I am a novice at regex can you take a look at this? The expression is [here](https://regex101.com/r/D5H8xT/1) and should match any valid number. I am receiving 0 matches once plugged into `std::regex_search`.

**Comment by jzmaddock** [comment]
Fixed in alternate PR, closing.

**Pull request closed without merging**
