### PR TITLE
adjust to move of gcd/lcm from math to integer library

### PR DESCRIPTION
**Pull request by jhunold**
The last changes, I hope.

### CODE REVIEW

**Comment by jzmaddock** [comment]
Um - wasn't this fixed already in your last PR?

**Comment by jhunold** [comment]
Oh, that is why I've had this deja-vu feeling.
It seems you accidentally reverted this in
 92748f63272088e6d97351ab49f4467638e6c713

**Comment by jzmaddock** [comment]
How the blazes did I manage that?  Apologies!

**Pull request merged**
