### PR TITLE
Reduce testing resource usage

### PR DESCRIPTION
**Pull request by mborland**
See: https://github.com/boostorg/math/issues/964

### CODE REVIEW

**Comment by mborland** [comment]
This dropped the total computational time in CI by ~15%. @jzmaddock is there anything else you can think of off hand that might be worth conditionally disabling to save resources?

**Comment by jzmaddock** [comment]
> This dropped the total computational time in CI by ~15%. @jzmaddock is there anything else you can think of off hand that might be worth conditionally disabling to save resources?

Not off hand.  But we should probably have one MSVC and one clang runner running the MP tests too?

**Comment by mborland** [comment]
All three are covered with the latest commit.

**Comment by jzmaddock** [comment]
> All three are covered with the latest commit.

Thanks!

**Comment by mborland** [comment]
Drone failure is on the CI system's end.

**Pull request merged**
