### PR TITLE
Add macro to disable MSVC has_denorm deprecation warning

### PR DESCRIPTION
**Pull request by mborland**
Closes: #573

### CODE REVIEW

**Comment by jzmaddock** [comment]
Are we between a rock and a hard place here?  The problem with _SILENCE_CXX23_DENORM_DEPRECATION_WARNING is that it changes the std lib header and silences the warning everywhere including in user code.  We may also eventually have this issue with other std lib's as well.

I wonder what the correct thing to do is here, members like has_denorm is still required to be present in C++23 but is "a candidate for removal" in a later std.  So we do need to define those members even in C++23 :(  I wonder if there any #pragma warning(disable:XXXX) that would work in this case?

**Comment by mborland** [comment]
> Are we between a rock and a hard place here? The problem with _SILENCE_CXX23_DENORM_DEPRECATION_WARNING is that it changes the std lib header and silences the warning everywhere including in user code. We may also eventually have this issue with other std lib's as well.
> 
> I wonder what the correct thing to do is here, members like has_denorm is still required to be present in C++23 but is "a candidate for removal" in a later std. So we do need to define those members even in C++23 :( I wonder if there any #pragma warning(disable:XXXX) that would work in this case?

We are between a rock and a hard place. I tried disabling the warning, and it still propagates: https://godbolt.org/z/bz1a54jf7

**Comment by jzmaddock** [comment]
Shucks :(

The macro doesn't work either if <limits> has already been included: https://godbolt.org/z/r6Pdn71We

**Comment by jzmaddock** [comment]
The #pragma does seem to work in some situations and not others... will experiment.

**Comment by jzmaddock** [comment]
This seems to get it: https://github.com/boostorg/multiprecision/pull/575

**Pull request closed without merging**
