### PR TITLE
Try (with minimal effort) GCC4 in arithmetic tests

### PR DESCRIPTION
**Pull request by ckormanyos**

### CODE REVIEW

**Comment by ckormanyos** [comment]
The result of this PR so far is:

- Do not include GCC 4.8 runs in CI.
- Make a separate file `detail/check_cpp11_config.hpp` capable of local specialization if needed.
- Repair numerous instances of mismatch `const`-versus-`constexpr`.
- Repair consistency in all header guards according to use `BOOST_MP_`-plus-filename-`_HPP` and optionally add uniqueness (e.g. `_DETAIL`) as needed.

**Comment by ckormanyos** [comment]
Hi John (@jzmaddock) this thing is review-ready. I'll struggle no further on it until we reach a 4.8 consensus. At the moment there is no effort to fully incorporate 4.8.

This PR in this state officially closes #429. You can, however, also choose to pursue this thread further. I'm OK with that too. Or later get back on it, or whatever?

I do, however, really want the changes within and as sketched/described above. Also a few changes in Math needed, as these are bugs anyway, I'll PR them shortly.

Tell me what you think...? And we can move on.

Cc: @mborland and @NAThompson

**Comment by ckormanyos** [comment]
Any feedback on this? It seems to be running green in CI.

**Comment by jzmaddock** [comment]
Sorry for the delay, yep, go for it!

**Comment by ckormanyos** [comment]
>  yep, go for it!

Thanks John. This PR ended up to not go entirely for GCC 4.8 and there is no 48. added run in CI. Multiprecision was pretty close to accepting 4.8, but a few small issues prevented that.

GCC 4.8 did find some inconsistencies (mostly `const`-versus-`constexpr`) as mentioned above and this PR resolves these nicely.

Cc: @mborland and @NAThompson

**Pull request merged**
