### PR TITLE
Workaround for over-sized object files on Mingw.

### PR DESCRIPTION
**Pull request by jzmaddock**
Fixes https://github.com/boostorg/multiprecision/issues/219

### CODE REVIEW

**Comment by jzmaddock** [comment]
@pabristow : you should see the command line as:

```
 "g++"   -fvisibility-inlines-hidden -m64 -mthreads -O0 -fno-inline -Wall -fvisibility=hidden -Wa,-mbig-obj -Wno-missing-braces -DBOOST_ALL_NO_LIB=1  -I"..\..\.." -I"..\include"  -c -o "..\..\..\bin.v2\libs\multiprecision\example\floating_point_examples.test\gcc-9.2\debug\debug-symbols-off\threading-multi\visibility-hidden\floating_point_examples.o" "floating_point_examples.cpp"
```

Which works for me with MSys64 GCC-9.2, but it is right on the limit :(

**Comment by pabristow** [comment]
I can confirm that 9.2.0 works OK, so your fix is correct, for which thanks.

But GCC 10 looks like the straw that breaks the camels back :-(

Is it time to break down the floating_point_examples to smaller examples?

Shall I investigate?  Where does it report the fraction of table size used?

**Comment by pabristow** [comment]
You asked about the command line, but it is now lost, and because I was on a detached HEAD, I seem not to have the log file for my failure.  Perhaps I can retry after you have merged big_obj changes to develop to make sure we are both using the same code?  What is the off option? that you added?

**Comment by eldiener** [comment]
You can always see the command line which b2 generates to build anything by passing the -d2 switch to the b2 invocation.

I am waiting for this PR to merge before testing it out with gcc on Windows. I have all recent released versions of gcc on which I can easily test, but I do not have 10.0 since it has not been officially released. I can probably build 10.0 from https://github.com/niXman/mingw-builds but I have learned that for my sanity playing around with non-released software is rarely productive for me. But occasionally I do, as in Visual Studio 2019 Preview where Microsoft has a really easy to use GUI for keeping it up to date.

**Comment by jzmaddock** [comment]
Merging now, like @eldiener I tend to ignore pre-release gcc versions as they often have multiple issues which ultimately get fixed.

**Comment by eldiener** [comment]
I tested mingw-w64/gcc-9.3 on Windows 10 and your fix works for the floating_point_examples. Thanks !

**Pull request merged**
