### PR TITLE
Fix for specfun_float128 tests

### PR DESCRIPTION
**Pull request by mborland**
This passes locally with the build flags copied from the circleci run.

### CODE REVIEW

**Comment by mborland** [comment]
@jzmaddock This is clean with GHA; hopefully that translates to CircleCI...

**Comment by jzmaddock** [comment]
Looks like I had builds from forked PR's turned off on the circle CI run, so fixed that and merged this.

**Comment by mborland** [comment]
[CircleCI results are green again](https://app.circleci.com/pipelines/github/boostorg/multiprecision/610/workflows/594c7854-644a-4fad-99b3-6bd1556409bc)

**Comment by jzmaddock** [comment]
Thanks Matt!

**Pull request merged**
