### PR TITLE
explicitly check for ARM/ARM64 on Windows

### PR DESCRIPTION
**Pull request by tailsu**
Tentative fix for https://github.com/boostorg/multiprecision/issues/475

### CODE REVIEW

**Comment by ckormanyos** [comment]
Thanks for looking into this @tailsu.

I have approved the CI run (for first-time contributors).

There was some similar discussion a few months ago, si we need to ask @jzmaddock if this is a similar case and if the fix is OK.

**Comment by tailsu** [comment]
OK, I'm glad 👍 

It would also make sense to add the compiler/platform combo to CI but I'm not sure how to do that.

**Comment by mborland** [comment]
@jzmaddock and @ckormanyos this should probably make the release as well since it is linked to multiple issues now.

**Comment by ckormanyos** [comment]
Thanks @tailsu, John and Matt for driving this forward.

**Pull request merged**
