### PR TITLE
PSLQ Algorithm

### PR DESCRIPTION
**Pull request by NAThompson**
Don't bother looking at this yet; I'm just making a PR so I can work on it from multiple computers and simultaneously shame myself into finishing it.

### CODE REVIEW

**Comment by ckormanyos** [comment]
> Don't bother looking at this yet

Well, against your advice, I did want to at least start compiling an example. I selected `cpp_dec_float` at 100 decimal digits and the constant `pi + ln_two`.

But I ran into this error:
`Cannot open include file: 'Eigen/Dense': No such file...`

Do I need a particular branch of Boost.Math in order to find Eigen/Dense?
Or I can ease off on this one for a while if that is preferred?

```
#include <iostream>
#include <map>
#include <string>

#include <boost/multiprecision/pslq.hpp>
#include <boost/multiprecision/cpp_dec_float.hpp>

namespace test_pslq
{
  using big_float_type = boost::multiprecision::number<boost::multiprecision::cpp_dec_float<100>,
                                                       boost::multiprecision::et_off>;

  // N[Pi + Log[2], 101]
  const std::string str_pi_plus_ln2_101
  {
    "3.8347398341497385478798755047376794522726695337353610750956246018012100282559037142338981523385357555"
  };
}

int main()
{
  using pslq_map_type = std::map<test_pslq::big_float_type, std::string>;

  std::map<test_pslq::big_float_type, std::string> m =
    boost::multiprecision::small_pslq_dictionary<typename pslq_map_type::value_type::first_type>();

  auto s = boost::multiprecision::pslq<typename pslq_map_type::value_type::first_type>(m);
}
```

**Comment by NAThompson** [comment]
@ckormanyos : I'm using the [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) matrix library right now to do the matrix reductions. I hope to eliminate that dependency before merging, which I now believe to be very achievable.

**Comment by NAThompson** [comment]
@ckormanyos : Go ahead and give this a try. It's not super fast, but it is much faster than Mathematica and Maple, as well as returning way fewer spurious relations.

I haven't been able to test the windows version; I just stackoverflow programmed it and hope for the best; would be nice to see it work.

**Comment by NAThompson** [comment]
I pwned this branch with a bad merge; squashed these commits into pslq_2.

**Pull request closed without merging**
