### PR TITLE
Add CodeCov badge for develop

### PR DESCRIPTION
**Pull request by ckormanyos**
Hi @jzmaddock and @mborland I hope you like this as much as I do. I would like quick access and clear visibility for the CodeCov achievements on the front cover ReadMe.

Can we do this? Do we really need table entries for develop/master? Or should i make a separate viewing area for a single CodeCov badge?

### CODE REVIEW

**Comment by ckormanyos** [comment]
It looks like the following on the page.

grafik

**Comment by mborland** [comment]
I would do one for develop and one for master. Release is in a few weeks so they will both be populated shortly. John is pushing hard on improving math coverage so I think it makes sense to show the delta between the two during the development period.

**Comment by ckormanyos** [comment]
The badge(s) are in.

I also added a (admittedly somewhat subjectively selected) section on _Using_ _Multiprecision_, which I personally would find helpful. It also links to GodBolt.

Like/Disapprove/Don't-Care about the new section? We can retain or modify or delete accordingly. Comments?

Cc: @jzmaddock and @mborland

**Comment by mborland** [comment]
> The badge(s) are in.
> 
> 
> 
> I also added a (admittedly somewhat subjectively selected) section on _Using_ _Multiprecision_, which I personally would find helpful. It also links to GodBolt.
> 
> 
> 
> Like/Disapprove/Don't-Care about the new section? We can retain or modify or delete accordingly. Comments?
> 

I can see it being a useful addition.

**Pull request merged**
