### PR TITLE
Remove uses of Boost.Array

### PR DESCRIPTION
**Pull request by mborland**
Closes: #567

### CODE REVIEW

**Comment by jzmaddock** [comment]
Not sure why this worked before... apparently boost::rational has no swap non-member, so we need a using std::swap in the test case.

**Comment by mborland** [comment]
@jzmaddock Any idea why the following now pops up in GNU mode?


```
../../../boost/math/special_functions/beta.hpp:573:35: error: call of overloaded 'log1p(boost::multiprecision::number<boost::multiprecision::backends::mpfr_float_backend<100>, (boost::multiprecision::expression_template_option)0>)' is ambiguous
             power1 = exp(a * log1p((x * b - y * a) / a + p * (x * c / a)));
```

**Comment by jzmaddock** [comment]
That's weird, and new :(

Not just gnu mode as the clang tests are failing too, I'll see if I can reproduce....

**Comment by jzmaddock** [comment]
Fix here: https://github.com/boostorg/math/pull/1043

**Comment by mborland** [comment]
> Fix here: [boostorg/math#1043](https://github.com/boostorg/math/pull/1043)

Thank you. Once that is merged I will re-run the CI here.

**Pull request merged**
