### PR TITLE
Remove leading zeros from base-10 numbers

### PR DESCRIPTION
**Pull request by mborland**
Currently we assume that anything with a leading 0 is in octal format. Change to where octal has to be 0 followed by a non-zero number. If the format does not meet that requirement for octal than remove any and all leading zeros.

Closes: #612

### CODE REVIEW

**Comment by ckormanyos** [comment]
> Change to where octal has to be 0 followed by a non-zero number.

Ah now I get it.

**Comment by mborland** [comment]
@jzmaddock Any issue with this change? It would technically be a breaking change, but I think the new behavior is less surprising.

**Review by ohhmm — APPROVED** [review]

**Comment by jzmaddock** [comment]
> Any issue with this change? It would technically be a breaking change, but I think the new behavior is less surprising.

I do worry about this, consider a block of formatted numbers:

```
0001
0002
0003
...
0099
0100
```

We start off as decimal, and then there is a step change to octal when we get to "0100" which seems even worse to me?

**Comment by mborland** [comment]
Godbolt says leading zeros is still octal: https://godbolt.org/z/7Kcahjh67. Since the original ticket is closed I'll just close this too.

**Comment by ckormanyos** [comment]
> start off as decimal, and then there is a step change to octal 

Oh geez I actually had that one last century. It took 3 days to resolve. But now that I reflecrt (which i had entirely forgotten) so is the spec.

**Pull request closed without merging**
